version: '3'
services:

  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc-ng-dev
    volumes:
      - mongo-data-dev:/data/db
    ports:
      - 127.0.0.1:27017:27017
    restart: always
    environment:
      - MONGO_DB:pwndoc
    networks:
      - backend

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    container_name: pwndoc-ng-backend-dev
    entrypoint: ""
    working_dir: "/app"
    command: "npm run dev"
    volumes:
      - ./backend/src/:/app/src/
      - ./backend/report-templates/:/app/report-templates/
      - ./backend/ssl/:/app/ssl/
      - ./backend/tests/:/app/tests/
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - ./backend/swagger.js:/app/swagger.js
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=dev
      - COLLAB_WEBSOCKET_PORT=8440
    restart: always
    ports:
      - 5252:5252
      - 8440:8440
    links:
      - mongodb
    networks:
      - backend

  frontend-app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: pwndoc-ng-frontend-dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/ssl:/app/ssl
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/index.html:/app/index.html
      - ./frontend/src/styles:/app/src/styles
    environment:
      - NODE_ENV=dev
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - backend
    networks:
      - backend

  frontend:
    image: nginx:stable-alpine
    container_name: pwndoc-ng-frontend-proxy
    user: root
    volumes:
      - ./frontend/.docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/ssl:/etc/nginx/ssl/
    restart: always
    ports:
      - 8443:8443
    depends_on:
      - frontend-app
      - backend
    links:
      - frontend-app
      - backend
    networks:
      - backend

  languagetool:
    image: erikvl87/languagetool
    container_name: pwndoc-ng-languagetool-dev
    restart: always
    networks:
      - backend

volumes:
  mongo-data-dev:

networks:
  backend:
    driver: bridge
