<template>
  <div class="container mx-auto px-4 py-6 max-w-6xl">
    <Card>
      <CardHeader class="bg-slate-500 text-white rounded-t-lg">
        <CardTitle class="text-xl">{{ $t('updateUserInformation') }}</CardTitle>
      </CardHeader>
      <Separator />
      <CardContent class="p-6">
        <div class="grid md:grid-cols-2 gap-8">
          <!-- User Information Section -->
          <div class="space-y-6">
            <!-- Role Display -->
            <div class="flex items-center justify-between">
              <span class="font-medium">{{ $t('role') }}</span>
              <Badge 
                :variant="user.role === 'admin' ? 'destructive' : 'default'"
                class="text-white"
                :class="user.role === 'admin' ? 'bg-orange-500' : 'bg-blue-500'"
              >
                {{ user.role }}
              </Badge>
            </div>

            <!-- Username -->
            <div class="space-y-2">
              <label class="text-sm font-medium">{{ $t('username') }}</label>
              <Input
                v-model="user.username"
                :error="!!errors.username"
                :error-message="errors.username"
              />
            </div>

            <!-- First Name -->
            <div class="space-y-2">
              <label class="text-sm font-medium">{{ $t('firstname') }}</label>
              <Input
                v-model="user.firstname"
                :error="!!errors.firstname"
                :error-message="errors.firstname"
              />
            </div>

            <!-- Last Name -->
            <div class="space-y-2">
              <label class="text-sm font-medium">{{ $t('lastname') }}</label>
              <Input
                v-model="user.lastname"
                :error="!!errors.lastname"
                :error-message="errors.lastname"
              />
            </div>

            <!-- Email -->
            <div class="space-y-2">
              <label class="text-sm font-medium">Email</label>
              <Input v-model="user.email" />
            </div>

            <!-- Phone -->
            <div class="space-y-2">
              <label class="text-sm font-medium">Phone</label>
              <Input v-model="user.phone" />
            </div>

            <!-- Password Update Section -->
            <div class="space-y-4">
              <div 
                v-if="errors.newPassword" 
                class="text-sm text-destructive"
              >
                {{ errors.newPassword }}
              </div>
              
              <div class="grid grid-cols-2 gap-4">
                <div class="space-y-2">
                  <label class="text-sm font-medium">{{ $t('newPassword') }}</label>
                  <Input
                    ref="pwdUpdateRef"
                    v-model="user.newPassword"
                    type="password"
                  />
                </div>
                <div class="space-y-2">
                  <label class="text-sm font-medium">{{ $t('confirmPassword') }}</label>
                  <Input
                    v-model="user.confirmPassword"
                    type="password"
                  />
                </div>
              </div>
            </div>

            <!-- Current Password -->
            <div class="space-y-2">
              <label class="text-sm font-medium">{{ $t('currentPassword') }}</label>
              <div class="flex gap-2">
                <Input
                  v-model="user.currentPassword"
                  type="password"
                  :error="!!errors.currentPassword"
                  :error-message="errors.currentPassword"
                  @keyup.enter="updateProfile"
                  class="flex-1"
                />
                <Button 
                  variant="default" 
                  @click="updateProfile"
                >
                  {{ $t('btn.update') }}
                </Button>
              </div>
            </div>
          </div>

          <!-- Two-Factor Authentication Section -->
          <div class="space-y-6">
            <!-- TOTP Toggle -->
            <div class="flex items-center space-x-3">
              <Switch 
                :checked="totpEnabled"
                @update:checked="(value) => { totpEnabled = value; getTotpQrcode(); }"
                label="Two-factor authentication"
              />
            </div>

            <!-- Setup TOTP -->
            <template v-if="totpEnabled && !user.totpEnabled">
              <div class="space-y-4">
                <div class="text-sm text-muted-foreground">
                  <p class="mb-2">Each time you log in, you will need to use an additional code generated by an authenticator application.</p>
                  <ol class="list-decimal list-inside space-y-1">
                    <li>Install an Authenticator App from your phone's store.</li>
                    <li>Open the Authenticator App.</li>
                    <li>Tap the Add icon or the Begin Setup button.</li>
                    <li>Choose Scan a Barcode, and scan using your phone.</li>
                    <li>Enter the generated token below to check and enable TOTP.</li>
                  </ol>
                </div>
                
                <div class="flex justify-center">
                  <img 
                    v-if="totpQrcode"
                    :src="totpQrcode" 
                    alt="TOTP QR Code"
                    class="w-48 h-48 border rounded-lg"
                  />
                </div>

                <div class="space-y-2">
                  <label class="text-sm font-medium">TOTP Token</label>
                  <div class="flex gap-2">
                    <Input
                      ref="totpEnableInput"
                      v-model="totpToken"
                      maxlength="6"
                      placeholder="Enter 6-digit code"
                      @keyup.enter="setupTotp"
                      class="flex-1"
                    />
                    <Button 
                      variant="default" 
                      @click="setupTotp"
                    >
                      Enable
                    </Button>
                  </div>
                </div>
              </div>
            </template>

            <!-- TOTP Enabled Status -->
            <div v-if="totpEnabled && user.totpEnabled" class="text-sm text-muted-foreground">
              Your account is currently protected by 2 factor authentication.
            </div>

            <!-- Cancel TOTP -->
            <template v-if="!totpEnabled && user.totpEnabled">
              <div class="space-y-4">
                <div class="text-sm text-muted-foreground">
                  This action will disable the second authentication factor.
                </div>
                
                <div class="space-y-2">
                  <label class="text-sm font-medium">TOTP Token</label>
                  <div class="flex gap-2">
                    <Input
                      ref="totpDisableInput"
                      v-model="totpToken"
                      maxlength="6"
                      placeholder="Enter 6-digit code"
                      @keyup.enter="cancelTotp"
                      class="flex-1"
                    />
                    <Button 
                      variant="destructive" 
                      @click="cancelTotp"
                    >
                      Disable
                    </Button>
                  </div>
                </div>
              </div>
            </template>
          </div>
        </div>
      </CardContent>
    </Card>
  </div>
</template>

<script>
import { defineComponent, nextTick } from 'vue'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Switch } from '@/components/ui/switch'
import { Separator } from '@/components/ui/separator'

import { useToast } from '@/composables/useToast'
import UserService from '@/services/user'
import Utils from '@/services/utils'

import { $t } from '@/boot/i18n'

export default defineComponent({
  name: 'ProfilePage',
  
  components: {
    Card,
    CardContent,
    CardHeader,
    CardTitle,
    Button,
    Input,
    Badge,
    Switch,
    Separator,
  },

  data() {
    return {
      user: {},
      totpEnabled: false,
      totpQrcode: "",
      totpSecret: "",
      totpToken: "",
      errors: {
        username: "", 
        firstname: "", 
        lastname: "", 
        currentPassword: "", 
        newPassword: ""
      }
    }
  },

  mounted() {
    this.getProfile()
  },

  methods: {
    getProfile() {
      UserService.getProfile()
        .then((data) => {
          this.user = data.data.datas
          this.totpEnabled = this.user.totpEnabled
        })
        .catch((err) => {
          console.error(err)
          const { error } = useToast()
          error('Failed to load profile', 'Error')
        })
    },

    getTotpQrcode() {
      if (this.totpEnabled && !this.user.totpEnabled) {
        UserService.getTotpQrCode()
          .then((data) => {
            let res = data.data.datas
            this.totpQrcode = res.totpQrCode
            this.totpSecret = res.totpSecret
            nextTick(() => {
              this.$refs.totpEnableInput?.focus()
            })
          })
          .catch((err) => {
            console.error(err)
            const { error } = useToast()
            error('Failed to generate TOTP QR code', 'Error')
          })
      } else if (!this.totpEnabled && this.user.totpEnabled) {
        nextTick(() => {
          this.$refs.totpDisableInput?.focus()
        })
      } else {
        this.totpQrcode = ""
        this.totpSecret = ""
        this.totpToken = ""
      }
    },

    setupTotp() {
      UserService.setupTotp(this.totpToken, this.totpSecret)
        .then((data) => {
          this.user.totpEnabled = true
          this.totpToken = ""
          
          const { success } = useToast()
          success('TOTP successfully enabled')
        })
        .catch((err) => {
          const { error } = useToast()
          error('TOTP verification failed', 'Error')
        })
    },

    cancelTotp() {
      UserService.cancelTotp(this.totpToken)
        .then(() => {
          this.user.totpEnabled = false
          this.totpToken = ""
          
          const { success } = useToast()
          success('TOTP successfully disabled')
        })
        .catch(() => {
          const { error } = useToast()
          error('TOTP verification failed', 'Error')
        })
    },

    updateProfile() {
      this.cleanErrors()
      
      if (!this.user.username)
        this.errors.username = $t('msg.usernameRequired')
      if (!this.user.firstname)
        this.errors.firstname = $t('msg.firstnameRequired')
      if (!this.user.lastname)
        this.errors.lastname = $t('msg.lastnameRequired')
      if (!this.user.currentPassword)
        this.errors.currentPassword = $t('msg.currentPasswordRequired')
      if (this.user.newPassword || this.user.confirmPassword) {
        if (!Utils.strongPassword(this.user.newPassword))
          this.errors.newPassword = $t('msg.passwordComplexity')
        if (this.user.newPassword !== this.user.confirmPassword)
          this.errors.newPassword = $t('msg.confirmPasswordDifferents')
      }

      if (this.errors.username || this.errors.firstname || this.errors.lastname || 
          this.errors.currentPassword || this.errors.newPassword)
        return

      UserService.updateProfile(this.user)
        .then((data) => {
          UserService.refreshToken()
          
          const { success } = useToast()
          success($t('msg.profileUpdateOk'))
        })
        .catch((err) => {
          const { error } = useToast()
          error(err.response?.data?.datas || err.message || 'Update failed', 'Error')
        })
    },

    cleanErrors() {
      this.errors.username = ''
      this.errors.firstname = ''
      this.errors.lastname = ''
      this.errors.currentPassword = ''
      this.errors.newPassword = ''
    }
  }
})
</script>

<style scoped>
/* Custom styles if needed */
</style>